apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-argo-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/aadi308/wordpress-argocd.git
    path: wordpress
  destination: 
    server: https://kubernetes.default.svc
    namespace: wordpress

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true