{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  {{- if .Values.autoscaling.AdvancedSetting.enabled }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.autoscaling.AdvancedSetting.scaledown.stabilizationWindowSeconds | default 300 }}
      policies:
      - type: {{ .Values.autoscaling.AdvancedSetting.scaledown.policies.type | default "Percent" }}
        value: {{ .Values.autoscaling.AdvancedSetting.scaledown.policies.value | default 10 }}
        periodSeconds: {{ .Values.autoscaling.AdvancedSetting.scaledown.policies.periodSeconds | default 60 }}
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.autoscaling.AdvancedSetting.scaleup.stabilizationWindowSeconds | default 300 }}
      policies:
      - type: {{ .Values.autoscaling.AdvancedSetting.scaleup.policies.type | default "Percent" }}
        value: {{ .Values.autoscaling.AdvancedSetting.scaleup.policies.value | default 10 }}
        periodSeconds: {{ .Values.autoscaling.AdvancedSetting.scaleup.policies.periodSeconds | default 30 }}
  {{- end }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "wordpress.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas | default 3 }}
  metrics:
  {{- if .Values.autoscaling.memory }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage | default 80 }}
  {{- end }}
  {{- if .Values.autoscaling.cpu }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage | default 80 }}
  {{- end }}
{{- end }}
