apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: network-policy
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/provider: zerone   
    {{- if ( .Values.LoadBalancer.disabled ) }}          
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: projectcontour
    {{- else }}
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.contour.ingress.class }}
    {{- end }}
    - namespaceSelector:
        matchLabels:
          app: prometheus
