kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "wordpress.fullname" . }}-binding
  labels: {{- include "wordpress.labels" . | nindent 4 }}
spec:
  {{- if ne .Values.persistence.storageClass "default" }}   
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
